### ISSUE TITLE
一番左のセルが上に引っ張られる

### ISSUE THREAD

**Issue by nkuroda** [webcyou/fixed-table-js#24]
![image](https://cloud.githubusercontent.com/assets/1215551/25348170/539799d4-2958-11e7-9532-f881583cac0a.png)

**Comment by panicdragon** [comment]
@nkuroda 
うーん。これは、ライブラリ側で対応したくはない感じなんですよね。。
というか、厳しい感じなので、domの方で

```
<td>
  <div class="wrap">
    <div class="contents">
      ...
    </div>
  </div>
</td>
```

と、wrap要素を設けて頂いて、`display: flex;` 等で対応いただければと。。
丁度、ちょい前に haito君がこの問題に当たったので、伺って頂ければと！

**Comment by nkuroda** [comment]
@panicdragon roger!

**Comment by panicdragon** [comment]
すません＞＜
closeさせて頂きます mm
