### ISSUE TITLE
セルの幅を超える内容の場合に高さを伸ばしたい

### ISSUE THREAD

**Issue by dito** [webcyou/fixed-table-js#27]
![image](https://cloud.githubusercontent.com/assets/4264269/25415043/379165da-2a70-11e7-9ecb-086d9047d6be.png)

隠れてしまいます。

**Comment by panicdragon** [comment]
@jabropt
伸縮させたいという事？

**Comment by dito** [comment]
そうです。高さを改行に合わせて伸縮させたいです。
